# Flask settings
DEFAULT_FLASK_SERVER_NAME = '0.0.0.0'
DEFAULT_FLASK_SERVER_PORT = '5000'
DEFAULT_FLASK_DEBUG = 1

# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

# TF Serving container settings
DEFAULT_TF_W2P_SERVER_NAME = '0.0.0.0'
DEFAULT_TF_W2P_SERVER_PORT = 9000

# Word to phonetic settings
W2P_DIR = './word_to_phonetic/'
W2P_MODEL_TRANSLATE_SIGNATURE = 'get_phon'
W2P_MODEL_TRANSLATE_INPUTS_KEY = 'input'

W2P_MODEL_ATT_MATRICES_SIGNATURE = 'get_att_mats'
W2P_MODEL_ATT_MATRICES_INPUTS_KEY = 'input'
W2P_MODEL_ATT_MATRICES_INPUTS_KEY2 = 'phon'

FR_MODEL_NAME = 'w2p_fr'
FR_FILES = W2P_DIR + 'fr/'

ES_MODEL_NAME = 'w2p_es'
ES_FILES = W2P_DIR + 'es/'

EN_MODEL_NAME = 'w2p_en'
EN_FILES = W2P_DIR + 'en/'
EN_VOCAB_FILE = W2P_DIR + 'en/vocab'